name: Buildah build

on:
  push:
    branches:
      - 'master'

jobs:
  build:
    name: Build latest Image
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        arch: [amd64, arm64, 386, arm, arm/v6, arm/v7]

    steps:
    - uses: actions/checkout@v2

    - name: Prepare multiarch
      run: sudo podman run --rm --privileged multiarch/qemu-user-static --reset -p yes
          
    - name: Build latest image
      id: build-image
      uses: redhat-actions/buildah-build@v2
      with:
        image: test
        archs: ${{ matrix.arch }}
        tags: latest-${{ matrix.arch }}
        dockerfiles: |
          ./Dockerfile
