name: Buildah build

on:
  push:
    branches:
      - 'master'

jobs:
  build1804:
    name: Build Dockerfile Ubuntu 18.04
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    
    - name: show buildah info
      run: |
        buildah info --debug

    - name: Build image
      uses: redhat-actions/buildah-build@v2
      with:
        image: test
        tags: latest
        dockerfiles: |
          ./Dockerfile

  build2004:
    name: Build Dockerfile manual Ubuntu 20.04
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2

    - name: show buildah info
      run: |
        buildah info --debug

    - name: Build image
      uses: redhat-actions/buildah-build@v2
      with:
        image: test
        tags: latest
        dockerfiles: |
          ./Dockerfile

  build1804-manual:
    name: Build Dockerfile manual Ubuntu 18.04
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - name: build manual
      run: |
        buildah bud -t test .

  build2004-manual:
    name: Build Dockerfile manual Ubuntu 20.04
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: build manual
      run: |
        sudo apt-get update
        apt-cache madison buildah
        sudo apt-get -y install buildah=1.19.8
        buildah bud -t test .
